"""empty message

Revision ID: 45784b0f68c7
Revises: 
Create Date: 2022-12-22 19:29:15.622055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45784b0f68c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('picture_url', sa.String(length=255), nullable=True),
    sa.Column('picture_name', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('entry_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('role', sa.Enum('visitor', 'recruiter', 'admin', name='usertypes'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('emails_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('recruiter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('picture_url', sa.String(length=255), nullable=True),
    sa.Column('picture_name', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('entry_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('role', sa.Enum('visitor', 'recruiter', 'admin', name='usertypes'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('picture_url', sa.String(length=255), nullable=True),
    sa.Column('picture_name', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('entry_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('role', sa.Enum('visitor', 'recruiter', 'admin', name='usertypes'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture_url', sa.String(length=255), nullable=True),
    sa.Column('picture_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('recruiter_email', sa.String(length=30), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiter.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_table('user')
    op.drop_table('recruiter')
    op.drop_table('emails_model')
    op.drop_table('admin')
    # ### end Alembic commands ###
