"""unique title for jobs

Revision ID: 88fb05f2730c
Revises: f64c59e7747e
Create Date: 2022-12-19 14:33:55.062181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fb05f2730c'
down_revision = 'f64c59e7747e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'job', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='unique')
    # ### end Alembic commands ###
