"""adding email to job model

Revision ID: f64c59e7747e
Revises: 78cb0b351483
Create Date: 2022-12-10 22:08:31.290576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64c59e7747e'
down_revision = '78cb0b351483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('recruiter_email', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'recruiter_email')
    # ### end Alembic commands ###
